### ISSUE TITLE
Introspection schema downloading with graphql-java-servlet not work

### ISSUE THREAD

**Issue by bonobonohu** [aoudiamoncef/apollo-client-maven-plugin#12]
hi!

i set up my graphql endpoint as:
```<schemaUrl>http://localhost:9091/graphql</schemaUrl>```
then i get:
```
Caused by: org.apache.maven.plugin.MojoExecutionException: Error, can't generate introspection schema file from: http://localhost:9091/graphql
    at com.lahzouz.java.graphql.client.maven.plugin.GraphQLClientMojo.execute (GraphQLClientMojo.kt:123)
```
the log on my console says:
```
graphql.execution.UnknownOperationException: Unknown operation named 'introspection'.
```

can you heal this, please?
(i'm using graphql-java-kickstart/graphql-java-servlet, so, if you simply send a GET request to "/graphql/schema.json", would be far enough, i think.)
(en fact, i implemented the same endpoint, which accepts POST requests (because graphql-java-servlet's works only with GET, damn! and you are sending POST with an introspeciton query), and it worked perfectly.)
(maybe the new methodology should be set up/activated with new configuration value(s)?)

thx, Ders

**Comment by Sparow199** [comment]
@bonobonohu,
I've added the most used way to get introspection query which will work with all GraphQL servers.

**Comment by bonobonohu** [comment]
i see, your title is definitely more accurate, thank you! 😉

**Comment by Sam-Kruglov** [comment]
Hi @aoudiamoncef, getting the same thing on `graphql-kickstart-spring-boot-starter-webflux`
```
graphql.execution.UnknownOperationException: Unknown operation named 'introspection'.
	at graphql.language.NodeUtil.getOperation(NodeUtil.java:85) ~[graphql-java-13.0.jar:?]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ HTTP POST "/graphql" [ExceptionHandlingWebHandler]
Stack trace:
		at graphql.language.NodeUtil.getOperation(NodeUtil.java:85) ~[graphql-java-13.0.jar:?]
		at graphql.execution.Execution.execute(Execution.java:62) ~[graphql-java-13.0.jar:?]
		at graphql.GraphQL.execute(GraphQL.java:605) ~[graphql-java-13.0.jar:?]
		at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:538) ~[graphql-java-13.0.jar:?]
		at graphql.GraphQL.executeAsync(GraphQL.java:502) ~[graphql-java-13.0.jar:?]
```

**Comment by Sam-Kruglov** [comment]
I looked with a debugger, the valid operation name for this case would be `IntrospectionQuery` instead of `introspection`

**Comment by Sam-Kruglov** [comment]
Another point, according to `graphql.kickstart.execution.GraphQLRequest#createIntrospectionRequest` you can actually leave `operationName` as `null` and it should work

**Comment by Sam-Kruglov** [comment]
Looks like this goes all the way down to `graphql-java` project.
Maybe you can just take this constant for your introspection? https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/introspection/Introspection.java

**Comment by aoudiamoncef** [comment]
Hi, I think that we should set operation name to null in order to support
all kind of GraphQL servers.

**Comment by Sam-Kruglov** [comment]
Great, can we do that? 

Also, the issue @bonobonohu mentioned with POST lies in the content type but it is the server fault (see the linked issue)

**Comment by aoudiamoncef** [comment]
Hi @Sam-Kruglov,
I read the [code ](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/language/NodeUtil.java) responsible of parsing GraphQL operation name and i think that the UnknownOperationException exception Unknown operation named is thrown when in your POST body you doesn't match `operationName` key.
I'll propose a solution for this issue.

**Comment by Sam-Kruglov** [comment]
Thanks! Please, also read my messages (2nd, 3rd, and 4th), I also mentioned this and provided some solutions

**Comment by Sam-Kruglov** [comment]
Works for me right now with 2.4.2. But if I want to say both of these things, it fails:
```
<generateIntrospectionFile>true</generateIntrospectionFile>
<introspectionFile>${project.build.directory}/graphql/schema.json</introspectionFile>
```
With just file generation it's fine, but if I want to generate it into a specific path, it fails. 
```
[INFO] Automatically generating introspection file from http://localhost:8080/graphql
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.870 s
[INFO] Finished at: 2020-04-16T19:22:19+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] .../project/target/graphql/schema.json (No such file or directory)
```
