### ISSUE TITLE
Error generating sources

### ISSUE THREAD

**Issue by heberrs** [aoudiamoncef/apollo-client-maven-plugin#13]
the generated query class package is getting a period (.) at the end of the name

example: 
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.graphql.client.;

**Comment by dantekind** [comment]
As a workaround, try putting your queries in a directory, such as `src/main/graphql/queries`

**Comment by Sparow199** [comment]
@heberrs , have you resolved this issue ? try to upgrade to latest version.
