### ISSUE TITLE
Packing the generated code into a jar

### ISSUE THREAD

**Issue by gaursagarMT** [aoudiamoncef/apollo-client-maven-plugin#14]
How can this library be used to make a jar of the generated sources?

**Comment by aoudiamoncef** [comment]
Hi @gaursagarMT ,
I'll try to add this feature ASAP.

**Comment by aoudiamoncef** [comment]
@gaursagarMT, 
I think that you have to handle this at project level. 

You should create a Maven library based on generated code:
[Maven library skeleton](https://github.com/JosemyAB/maven-library-skeleton/blob/master/pom.xml)
[Maven resource plugin](https://maven.apache.org/plugins/maven-resources-plugin/examples/copy-resources.html)

**Comment by gaursagarMT** [comment]
*late update alert* I ultimately didn't create a separate jar for queries.

I use this library to generate code directly in my source code and include the generated java classes as unmanaged sources. It's working out quite well. Thanks for maintaining this repository :D
