### ISSUE TITLE
Error in generated classes while using apollo-runtime version 1.2.2

### ISSUE THREAD

**Issue by gaursagarMT** [aoudiamoncef/apollo-client-maven-plugin#15]
I am getting the following error in my generated classes
```
Class 'MyClass' must either be declared abstract or implement abstract method 
'parse(BufferedSource, ScalarTypeAdapters)' in 'Operation'

```

with the following apollo-runtime, and apollo-client-plugin versions.
```   
<apollo-client-maven-plugin.version>2.2.0</apollo-client-maven-plugin.version>
<apollo-runtime.version>1.2.2</apollo-runtime.version>
```

Generated code works fine when using `apollo-runtime` version `>=1.2.1`
This issue seems to be due to a change in the signature of `com.apollographql.apollo.api.Operation` class between the two versions.

**Comment by aoudiamoncef** [comment]
Hi,
I remember that I got this issue when I did the last release, I deleted all
my artifacts from my Maven local repository and then the tests passed.
Clean up you current project and rebuild it and give it a try. Add the
latest added config explicitly <generateAsInternal>false</generateAsInternal
>
