### ISSUE TITLE
Cannot find the generated classes

### ISSUE THREAD

**Issue by addy419** [aoudiamoncef/apollo-client-maven-plugin#16]
To use the generated classes in Java.
I created a query named Info in src/main/graphql/Info.graphql
Then added schema.json in the same directory.
when I'm doing mvn compile or mvn generate-sources. The build is successful but I can't find the classes to import in my java code. where are they stored and are they actually being generated for me

**Comment by aoudiamoncef** [comment]
<configuration>
    <skip>false</skip>
    <addSourceRoot>true</addSourceRoot>
    <introspectionFile>${project.basedir}/src/main/graphql/schema.json</introspectionFile>
    <generateTransformedQueries>false</generateTransformedQueries>
    <transformedQueriesOutputDir>${project.build.directory}/generated-sources/graphql-client/transformedQueries</transformedQueriesOutputDir>
    <generateIntrospectionFile>false</generateIntrospectionFile>
    <sourceDirName>${project.basedir}/src/main/graphql</sourceDirName>
    <schemaUrl>http://localhost/graphql</schemaUrl>
    <rootPackageName>com.example.graphql.client</rootPackageName>
    <outputDirectory>${project.build.directory}/generated-sources/graphql-client</outputDirectory>
    <generateModelBuilder>true</generateModelBuilder>
    <useJavaBeansSemanticNaming>true</useJavaBeansSemanticNaming>
    <useSemanticNaming>true</useSemanticNaming>
    <nullableValueType>JAVA_OPTIONAL</nullableValueType>
    <suppressRawTypesWarning>false</suppressRawTypesWarning>
    <generateKotlinModels>false</generateKotlinModels>
    <generateAsInternal>false</generateAsInternal>
    <generateVisitorForPolymorphicDatatypes>false</generateVisitorForPolymorphicDatatypes>
    <customTypeMap></customTypeMap>
</configuration>

**Comment by aoudiamoncef** [comment]
<configuration> <skip>false</skip> <addSourceRoot>true</addSourceRoot> <introspectionFile>${project.basedir}/src/main/graphql/schema.json</introspectionFile> <generateTransformedQueries>false</generateTransformedQueries> <transformedQueriesOutputDir>${project.build.directory}/generated-sources/graphql-client/transformedQueries</transformedQueriesOutputDir> <generateIntrospectionFile>false</generateIntrospectionFile> <sourceDirName>${project.basedir}/src/main/graphql</sourceDirName> <schemaUrl>http://localhost/graphql</schemaUrl> <rootPackageName>com.example.graphql.client</rootPackageName> <outputDirectory>${project.build.directory}/generated-sources/graphql-client</outputDirectory> <generateModelBuilder>true</generateModelBuilder> <useJavaBeansSemanticNaming>true</useJavaBeansSemanticNaming> <useSemanticNaming>true</useSemanticNaming> <nullableValueType>JAVA_OPTIONAL</nullableValueType> <suppressRawTypesWarning>false</suppressRawTypesWarning> <generateKotlinModels>false</generateKotlinModels> <generateAsInternal>false</generateAsInternal> <generateVisitorForPolymorphicDatatypes>false</generateVisitorForPolymorphicDatatypes> <customTypeMap></customTypeMap> </configuration>

**Comment by aoudiamoncef** [comment]
<outputDirectory>${project.build.directory}/generated-sources/graphql-client</outputDirectory>

**Comment by addy419** [comment]
And how do I import them for use?

**Comment by aoudiamoncef** [comment]
You have nothing to worry about it, your IDE will do it for you. I'm using
Intellij, It's automatically import the generated classes.

**Comment by addy419** [comment]
The problem was with my maven plug-in placement, I did not not place it directly in plugins, it was inside plugin manager

**Comment by addy419** [comment]
The demo example helped.

**Comment by divvy123** [comment]
To generate classes in Java.
I created a query named Info in src/main/graphql/SampleTest.graphql
Then added schema.json in the same directory.
when I'm doing mvn compile or mvn generate-sources. The build is successful but doesnt generate classes.

I have placed the plugin thus:
	<build>
	    <pluginManagement>
		<plugins>
		    <plugin>
		        <groupId>com.github.aoudiamoncef</groupId>
		        <artifactId>apollo-client-maven-plugin</artifactId>
		        <version>4.0.5</version>
