### ISSUE TITLE
Generated objects/fields on Interfaces/Implementations

### ISSUE THREAD

**Issue by aveiros** [aoudiamoncef/apollo-client-maven-plugin#19]
Consider the following schema

```
type Test {
   items: [Item!]!
}

interface Item {
    id: String!
}

type ItemA implements Item {
    id: String!
    a: String!
}

type ItemB implements Item {
    id: String!
    b: String!
}

type Query {
    getTest: Test
}
```

**Case 1**
If we don't specify the concrete types on the query
```
getTest {
     items {
        id
     }
}
```
The java code for the items field is
```
List<Item>
```

**Case 2**
Once we specify the the concrete types on the query
```
getTest {
     items {
        id
       ... on ItemA {
          a
       }
       ... on ItemB {
          b
       }
     }
}
```
The java code for the items field is
```
Optional<List<Item>>
```

Actual: a field (non null) is optional, once concrete types are specified
Expected: a field (non null) is not optional, once concrete types are specified

**Comment by aoudiamoncef** [comment]
Hi @aveiros,

I think that your issue should is about the compiler part which is part of [Android Apollo](https://github.com/apollographql/apollo-android/issues). Feel free to create a new issue in the main project.
Thanks

**Comment by aveiros** [comment]
Thanks, closing this 👍
