### ISSUE TITLE
Query filter representing "match all"?

### ISSUE THREAD

**Issue by simonmarshall** [aoudiamoncef/apollo-client-maven-plugin#20]
Hi, we're using the plugin to generate Java classes from our query specs, and it's very useful, thank you.  However, I've got a question regarding (empty) query filters.

If I generate a query class `Q` with corresponding filter input class `F`, such that `Q`'s ctor takes an `F` instance, then I can filter on field `foo` for some value `f` like so:

`F.Builder filter = F.builder().foo(...builder().eq(f).build());`
`new Q(filter.build());`

This is nice.  However, if I'm trying to build my filter from a list of optional things over which I have no control, then I may have an empty filter, as if I had done:

`F.Builder filter = F.builder();`
`new Q(filter.build());`

This un-intuitively matches nothing on the server, whereas I would expect it to match everything.

The only way I can see to make this work is by making the filter be optional, such that `Q`'s ctor takes an  `Input<F>` instance, and using `Input.absent()` when there is nothing to filter on.  However, this means I have to keep track of whether I have any actual things to use in a filter, which is messy.  For example, if I have 4 things I can filter on in `F`, I have to use an `Input.absent()` if all of the things are `null`, and build an actual `Input<F>` otherwise.

Ideally, I would like an empty filter to match everything, but I don't know if that's a bug or a feature.

Or is there a better way?

**Comment by aoudiamoncef** [comment]
Hi @simonmarshall,

I think that your issue should is about the compiler part which is part of [Android Apollo](https://github.com/apollographql/apollo-android/issues). Feel free to create a new issue in the main project.
Thanks

**Comment by simonmarshall** [comment]
thanks, fwiw, raised as [issue 1961](https://github.com/apollographql/apollo-android/issues/1961)
