### ISSUE TITLE
Apollo 1.3.x support?

### ISSUE THREAD

**Issue by aveiros** [aoudiamoncef/apollo-client-maven-plugin#21]
Any plans for Apollo 1.3.x?

**Comment by aoudiamoncef** [comment]
Hi, I'll migrate ASAP

**Comment by aoudiamoncef** [comment]
Hi @aveiros ,
[v2.3.0](https://github.com/aoudiamoncef/apollo-client-maven-plugin/releases/tag/v2.3.0) is available on JCenter && Maven central.
