### ISSUE TITLE
Unable to generate classes for recursive tree structures 

### ISSUE THREAD

**Issue by me-hek** [aoudiamoncef/apollo-client-maven-plugin#23]
Hi,

I am having issues generating classes with below error. Would like to label this as a question.

**Can't query `Info` on type `Info`**
Sample

**Info.graphqls**
extend type Query {
    listSomeInfo(userId: String!): [Info!]
}

type **Info** {
    id: ID!
    name: String!
    desription: String!
    children: [**Info**!]
    parent: **Info**
}

**Info.graphql**
query (
    $userId: String!
) {
    listSomeInfo(
        userId: $userId
    ) {
        id
        name
        desription
        children: **Info** {
            id
            name
            children: **Info** {
                id,
		name
            }
            parent: **Info** {
                id,
		name
            }
        }
    }
}

**Comment by aoudiamoncef** [comment]
Hi @me-hek ,
I think that you have to report this issue to the main project which is [Apollo Android](https://github.com/apollographql/apollo-android/issues )
