### ISSUE TITLE
invalid url to introspection gist

### ISSUE THREAD

**Issue by davidkarlsen** [aoudiamoncef/apollo-client-maven-plugin#25]
there is a link in the docs to the introspection query: `https://gist.github.com/Sparow199/a59527016e16a2d56309d62e01ff2348` but this gist does not exist

**Comment by aoudiamoncef** [comment]
Hi,
I changed my Github account name and it seems that the redirection doesn't
work for gists.

https://gist.github.com/aoudiamoncef/a59527016e16a2d56309d62e01ff2348
