### ISSUE TITLE
Plugin in execution not covered error with plugin

### ISSUE THREAD

**Issue by seesiva** [aoudiamoncef/apollo-client-maven-plugin#27]
Planning to adopt this plugin for Java server application, when following the plugin instructions getting the following error. Any advice?

```
Plugin execution not covered by lifecycle configuration: com.github.sparow199:apollo-client-maven-plugin:3.0.3:generate (execution: default, phase: generate-sources)	pom.xml	/server	line 72	Maven Project Build Lifecycle Mapping Problem
```

**Comment by aoudiamoncef** [comment]
Hi @seesiva ,
Are you using Eclipse ? 

Try to use [this](https://github.com/aoudiamoncef/spring-boot-mvc-apollo-graphql/blob/master/pom.xml) project with the latest version of the plugin.

**Comment by seesiva** [comment]
@aoudiamoncef Thanks for sharing this link. I'm using Eclipse.

**Comment by aoudiamoncef** [comment]
@seesiva, i think that it's an Eclipse maven issue, try to look at this [solution](https://stackoverflow.com/questions/7391201/plugin-error-execution-not-covered-by-lifecycle-configuration/7392705#7392705)

**Comment by seesiva** [comment]
@aoudiamoncef I will try to resolve based on it and will keep posted here.

**Comment by seesiva** [comment]
> @aoudiamoncef I will try to resolve based on it and will keep posted here.

After this build is getting failed stating that given mutation is not found. Also it has error when we are having Custom Scalar type.

**Comment by aoudiamoncef** [comment]
@seesiva, i think this issues are related to the main project, please create an issue in [apollo android ](https://github.com/apollographql/apollo-android/issues) projet.

**Comment by seesiva** [comment]
@aoudiamoncef Thanks. Sure.

**Comment by aoudiamoncef** [comment]
I'm releasing the plugin with latest version of Apollo compiler, give it a try. it will be available in few hours on maven central.

**Comment by seesiva** [comment]
@aoudiamoncef ok sure, will try.

**Comment by seesiva** [comment]
> I'm releasing the plugin with latest version of Apollo compiler, give it a try. it will be available in few hours on maven central.

I felt like couple of days back it was working and generating the source automatically and may be I have also messed up the pom.xml. I'm also trying to figure it.
