### ISSUE TITLE
Failed to locate schema root node `__schema`

### ISSUE THREAD

**Issue by freison** [aoudiamoncef/apollo-client-maven-plugin#28]
generate failed: Failed to parse GraphQL schema introspection query from

**Comment by aoudiamoncef** [comment]
Hi @freison ,
Could you please give me more details ?

**Comment by rmeruva29** [comment]
Hi, I'm also running into the same error which is "[ERROR] Failed to execute goal com.github.sparow199:apollo-client-maven-plugin:3.2.2:generate (default) on project xxx: Execution default of goal com.github.sparow199:apollo-client-maven-plugin:3.2.2:generate failed: Failed to parse GraphQL schema introspection query from `/Users/rmeruva/xxx/src/main/graphql/schema.json`: Failed to locate schema root node `__schema` -> [Help 1]"...Attaching the schema.json and query file (in txt format)
[schema.txt](https://github.com/aoudiamoncef/apollo-client-maven-plugin/files/5058251/schema.txt)
[launchList.txt](https://github.com/aoudiamoncef/apollo-client-maven-plugin/files/5058259/launchList.txt)

I don't see this error when I use the schema provided in one of your examples.

Thanks
