### ISSUE TITLE
Prettify output schema.json

### ISSUE THREAD

**Issue by overmike** [aoudiamoncef/apollo-client-maven-plugin#29]
Are there any concern to prettify the output schema.json instead of single long line?

Pros
- Human readable
- VCS Diff friendly

Cons
- Larger in size

**Comment by aoudiamoncef** [comment]
Hi @overmike ,

I'll add this feature in the next release.

**Comment by overmike** [comment]
Cool Thanks!

**Comment by aoudiamoncef** [comment]
Hi @overmike 

It's available in v4+

Thanks
