### ISSUE TITLE
Failed to locate schema root node `__schema`

### ISSUE THREAD

**Issue by rmeruva29** [aoudiamoncef/apollo-client-maven-plugin#31]
Hi, I'm running into this error "[ERROR] Failed to execute goal com.github.sparow199:apollo-client-maven-plugin:3.2.2:generate (default) on project xxx: Execution default of goal com.github.sparow199:apollo-client-maven-plugin:3.2.2:generate failed: Failed to parse GraphQL schema introspection query from `/Users/rmeruva/xxx/src/main/graphql/schema.json`: Failed to locate schema root node `__schema` -> [Help 1]"...Attaching the schema.json and query file (in txt format)
[schema.txt](https://github.com/aoudiamoncef/apollo-client-maven-plugin/files/5058251/schema.txt)
[launchList.txt](https://github.com/aoudiamoncef/apollo-client-maven-plugin/files/5058259/launchList.txt)

I don't see this error when I use the schema provided in one of your examples(https://github.com/aoudiamoncef/spring-boot-mvc-apollo-graphql/tree/master/src/main/graphql).

Thanks

_Originally posted by @rmeruva29 in https://github.com/aoudiamoncef/apollo-client-maven-plugin/issues/28#issuecomment-672089052_

**Comment by aoudiamoncef** [comment]
Hi @rmeruva29,
Please use this introspection [query](https://gist.github.com/craigbeck/b90915d49fda19d5b2b17ead14dcd6da) to get a valid schema.

Your schema output has different keys names(without `_`) and doesn't contain the `data` wrapper object...etc

**Comment by rmeruva29** [comment]
That worked...thanks
