### ISSUE TITLE
Failed to parse GraphQL file

### ISSUE THREAD

**Issue by MarouaniHani** [aoudiamoncef/apollo-client-maven-plugin#32]
Hello, i followed all the steps in the docs and i had an issue  "Failed to parse GraphQL file /home/hany/java/projects-be/src/main/graphql/GetBooks.graphql (2:4)
[ERROR] Can't query `books` on type `Query`"
can you help me with it please ?

**Comment by aoudiamoncef** [comment]
Hi @MarouaniHani,

Sorry for the late reply. It should be fixed with version 4+. 

Thanks
