### ISSUE TITLE
rootPackageName configuration seems ignored

### ISSUE THREAD

**Issue by jpastoor** [aoudiamoncef/apollo-client-maven-plugin#34]
The code is generated in the `com.example.graphql.client`, instead of using the configuration option `rootPackageName`. Am I missing something or is this a bug?

Currently using 
```
        <apollo-client-maven-plugin.version>3.3.1</apollo-client-maven-plugin.version>
        <apollo-runtime.version>2.3.1</apollo-runtime.version>
```

with the following plugin configuration:
```
<plugin>
                <groupId>com.github.sparow199</groupId>
                <artifactId>apollo-client-maven-plugin</artifactId>
                <version>${apollo-client-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <rootPackageName>org.mycompany.xxx.graphql.client</rootPackageName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

Generated sources have the `com.example.graphql.client` package. mvn clean and re-generate did not resolve the issue. (I'm pretty rusty when it comes to Java so good chance I'm doing something wrong here :) )

**Comment by jpastoor** [comment]
Found out that it does seem to work whenever I move the configuration to the plugin top level, instead of in the execution block.

```
            <plugin>
                <groupId>com.github.sparow199</groupId>
                <artifactId>apollo-client-maven-plugin</artifactId>
                <version>${apollo-client-maven-plugin.version}</version>
                <configuration>
                    <rootPackageName>org.mycompany.xxx.graphql.client</rootPackageName>
```
works.

is that expected?

**Comment by aoudiamoncef** [comment]
Hi @jpastoor,
This what's expected.

**Comment by jpastoor** [comment]
But in the README and in the example project the plugin configuration is present in the `<execution>` block, should we update the README and move the configuration there too?

**Comment by aoudiamoncef** [comment]
Please look at [Spring Boot example](https://www.github.com/aoudiamoncef/spring-boot-mvc-apollo-graphql/tree/master/pom.xml)
