### ISSUE TITLE
Directives at query or mutation locations not supported

### ISSUE THREAD

**Issue by jorgebay** [aoudiamoncef/apollo-client-maven-plugin#37]
The spec allows [directives  at `QUERY` and `MUTATION` locations](https://spec.graphql.org/June2018/#ExecutableDirectiveLocation) but code generation plugin doesn't.

For example, the following valid graphql is not supported by the plugin:

```
mutation @myModifier CreateReviewForEpisode($review: ReviewInput!) {
  val1: createReview(review: $review),
  val2: trackReview(review: $review),
}
```

**Comment by aoudiamoncef** [comment]
Please open an issue [Apollo Android](https://github.com/apollographql/apollo-android).

**Comment by jorgebay** [comment]
Thanks for the guidance, I've created a ticket there https://github.com/apollographql/apollo-android/issues/2661

**Comment by jorgebay** [comment]
TIL the correct order is the following:

```graphql
mutation CreateReviewForEpisode($review: ReviewInput!) @myModifier {
  val1: createReview(review: $review),
  val2: trackReview(review: $review),
}
```

With the directive after the name. It works as expected that way, sorry for the noise.
