### ISSUE TITLE
Schema introspection query handling null defaults

### ISSUE THREAD

**Issue by bollerdominik** [aoudiamoncef/apollo-client-maven-plugin#39]
I have a GraphQL scheme containing following definitions

```
input SomeType {
  id: String!
  title: String = null
  email: String = null
  reference: String = null
}
```

The given introspection query returns following for field `reference`

            {
              "name": "reference",
              "description": "Reference is invoice reference",
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "defaultValue": "null"
            },

The ` "defaultValue": "null"` results in a Java object with the String "null". However, I expect he field to be null.

defaultValue should be `null` and not `"null"`

**Comment by aoudiamoncef** [comment]
Hi @bollerdominik 

[Possible fix](https://github.com/apollographql/apollo-android/releases/tag/v2.4.4)
