### ISSUE TITLE
How is <schemaUrlHeaders/> working ?

### ISSUE THREAD

**Issue by KeligMartin** [aoudiamoncef/apollo-client-maven-plugin#41]
Hi, I want to genereate the schema.json file with introspection, i have my request in the right folder, working fine for a route without a needed header.

but when i want to set up the `<schemaUrlHeaders>` node i dont know how to use it. Is there a specific syntax?

Can you please guide me?

```
<plugin>
	<groupId>com.github.sparow199</groupId>
	<artifactId>apollo-client-maven-plugin</artifactId>
	<version>3.3.1</version>
	<executions>
		<execution>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<rootPackageName>api.graphql</rootPackageName>
				<outputDirectory>${project.basedir}/src/main/java</outputDirectory>
				<generateIntrospectionFile>true</generateIntrospectionFile>
				<schemaUrl>http://remote.server:8080/graphql</schemaUrl>
				<schemaUrlHeaders></schemaUrlHeaders>
			</configuration>
		</execution>
	</executions>
</plugin>
```

here is my pom.xml plugin node

**Comment by aoudiamoncef** [comment]
Hi @KeligMartin 
[Maven MOJOs maps](https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Mapping_Maps)
