### ISSUE TITLE
Malformed POM Error with `services` tag

### ISSUE THREAD

**Issue by flopes89** [aoudiamoncef/apollo-client-maven-plugin#47]
I tried to set up the plugin, but got this error when trying to run it:

```
Malformed POM D:\...\pom.xml: Unrecognised tag: 'services' (position: START_TAG seen ...</goals>\r\n<services>... @225:35)
```

What can I do here?

**Comment by aoudiamoncef** [comment]
Hi @flopes89 

Could you share your entire plugin configuration please ? 

There is a complete [example](https://github.com/aoudiamoncef/spring-boot-apollo-graphql/blob/main/pom.xml)

**Comment by michel-zedler** [comment]
Readme XML snipplet is missing the configuration element https://github.com/aoudiamoncef/apollo-client-maven-plugin/pull/48
