### ISSUE TITLE
Add Support For Generating package-private Java

### ISSUE THREAD

**Issue by SingleShot** [aoudiamoncef/apollo-client-maven-plugin#51]
Hi. We're using this library for generating the internal implementation of a hand-crafted client. We'd like to be able to generate all the code into a single package and have all Java classes be package-private visibility. The reason is we are trying to limit what our users see when auto-completing in an IDE when they’ve  use our client. We can generate the code into the same package as our hand-crafted classes, and it will be hidden from our users, but not from our hand-crafted implementation. Thanks.

**Comment by aoudiamoncef** [comment]
Hi @SingleShot,

Please make a feature request in  [Apollo Android](https://github.com/apollographql/apollo-android). 

It will be integrated in Maven plugin when Apollo 3.0.0 will be in the wild ✅

Thanks 👍
