### ISSUE TITLE
Dynamically Modify Query Fields

### ISSUE THREAD

**Issue by SingleShot** [aoudiamoncef/apollo-client-maven-plugin#52]
Hi. This is not an issue so much as a question. We have an interesting case where we allow our customers to create custom fields on objects. For example, a user object might have "firstName" and "lastName", but for one customer it also has "nickname" and for another customer "phoneNumber". They can add whatever they like. When a customer retrieves metadata we use their customer id to look up their custom fields specific to the customer to populate the metadata with. 

As you can imagine this doesn't work so well with generated query code. We can't generate code for every customer - even if we were willing to, the custom fields can be added at any time.

Can you advise if there is any area of the generated client code that would let us get in and modify the query string to inject these custom fields before it is sent over the wire, or perhaps to introduce some kind of decorator or subclass that we can add support for them? Thanks.

**Comment by aoudiamoncef** [comment]
Hi @SingleShot,

It's an interesting usecase. IMHO, it could be possible to add a list of paths or file glob  to be excludes by Apollo complier. 

Cc @martinbonnin

**Comment by aoudiamoncef** [comment]
To achieve what you need, there is a workaround, try to customize your schema file by removing excluded fields.
