### ISSUE TITLE
Blocking error when schema.json is not present in server side

### ISSUE THREAD

**Issue by ycharaf-adeo** [aoudiamoncef/apollo-client-maven-plugin#53]
When GraphQl server side does not have schema.json file, it is a blocking issue for apollo client. Knowing that is a best practice and not a mandatory, i think apollo client maven plugin should use it OPTIONNALLY

**Comment by aoudiamoncef** [comment]
Could you give a context please ? schema.json is mandatory, you could download it via Apollo Maven plugin or just copy and past it.

**Comment by ycharaf-adeo** [comment]
I need to call a GraphQl API with Apollo client in Java, Spring boot with Apollo Maven plugin. Their GraphQl API is not setting their schema.json. So the compilation is always on error. When i read the GraphQL documentation, i didn't see anywhere when it is specificly said "Mandatory"

**Comment by aoudiamoncef** [comment]
I see, 

You have to get introspection schema of your server, without it you can't generate anything.
