### ISSUE TITLE
Migration to Apollo Kotlin v3

### ISSUE THREAD

**Issue by pinguinjkeke** [aoudiamoncef/apollo-client-maven-plugin#54]
Code generation methods in Apollo Kotlin option is missing. Can it be added?

https://www.apollographql.com/docs/android/advanced/response-based-codegen/

**Comment by aoudiamoncef** [comment]
Hi @pinguinjkeke 

This is a part of Apollo 3.0.0 migration

**Comment by pinguinjkeke** [comment]
@aoudiamoncef any plans to migrate on it?

**Comment by aoudiamoncef** [comment]
It's not released yet. but yes, the migration is in progress

**Comment by pinguinjkeke** [comment]
Thanks for an answer.

You can close an issue or I can change it's description to something more v3 migration specific
