### ISSUE TITLE
Possible to play nice with maven offline-dependencies?

### ISSUE THREAD

**Issue by gcbw** [aoudiamoncef/apollo-client-maven-plugin#55]
after adding apollo-client-maven-plugin as a dependency on my pom.xml file, i cannot use maven offline dependency pattern.

e.g.
```
mvn dependency:go-offline
...
mvn --offline install
[INFO] --- apollo-client-maven-plugin:2.2.3:generate (default) @ project ---
[WARNING] The POM for org.apache.maven:maven-plugin-api:jar:3.6.0 is missing, no dependency information available
[WARNING] The POM for org.apache.maven:maven-project:jar:2.2.1 is missing, no dependency information available
[WARNING] The POM for com.apollographql.apollo:apollo-compiler:jar:1.2.3 is missing, no dependency information available
[WARNING] The POM for org.apache.httpcomponents:httpclient:jar:4.5.10 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------ 
```

I'm just starting to investigate this, but already posting here in case anyone have more insights already.

**Comment by gcbw** [comment]
added a small test case here showing the problem, but because of my employer network i can't use more recent versions. Will update this later.

https://github.com/gcbw/apollo-client-maven-plugin-offline

**Comment by aoudiamoncef** [comment]
Hi @gcbw,

Have tried tried [this](https://stackoverflow.com/questions/45730541/the-pom-for-is-missing-no-dependency-information-available-even-though-it) possible solution ?

**Comment by gcbw** [comment]
Interesting. I was going at it wrong. I assumed the plugin would select the needed jars after parsing the settings... but indeed, it have the dependencies laid out just fine and maven is indeed downloading the JARs but not the POMs. Weird. I asked [another question](https://stackoverflow.com/questions/70584250/maven-failing-to-download-pom-in-specific-cases) with more detail but I think you are right. nothing to do here.
Thanks!
