### ISSUE TITLE
Java 19

### ISSUE THREAD

**Issue by AndyGee** [aoudiamoncef/apollo-client-maven-plugin#66]
I have been unable to generate any Java code that will compile or is usable (type safe) on Java 19 - I haven't tried any earlier version, so really this is just a question to ask if type safe Java 19 is supported at all? 

Examples are scarce and I have exhausted the docs, which is why I've resorted to asking here.

**Comment by aoudiamoncef** [comment]
Hi @AndyGee,

I didn't upgrade the projet from a while, I quite busy with my current position. Feel free to contribute, I'll review and merge the PR.

**Comment by martinbonnin** [comment]
@AndyGee can you share what errors you're seeing? Does it compile with Java 11 or earlier?

**Comment by aoudiamoncef** [comment]
Hi @AndyGee any news about this issue ?
