### ISSUE TITLE
how to modify model class created by graph -ql ?

### ISSUE THREAD

**Issue by anilthummar** [aoudiamoncef/apollo-client-maven-plugin#68]
is any way to modify or update model class.
i want to changed val to var variable in data model class

**Comment by aoudiamoncef** [comment]
Hi @anilthummar,

I think that your issue should is about the compiler part which is part of [Apollo Kotlin](https://github.com/apollographql/Apollo-kit Lin/issues). Feel free to create a new issue in the main project.
Thanks
