### ISSUE TITLE
Migration to Gradle

### ISSUE THREAD

**Issue by psupelek** [aoudiamoncef/apollo-client-maven-plugin#88]
Have you considered migrating apollo-client-maven-plugin to Gradle?
I found the plugin very useful, however my requirement is to use Gradle.
I'm struggling with migrating the plugin part from pom.xml.

> <plugins>
            <plugin>
                <groupId>com.github.aoudiamoncef</groupId>
                <artifactId>apollo-client-maven-plugin</artifactId>
                <version>7.1.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <services>
                                <books-api>
                                    <enabled>true</enabled>
                                    <addSourceRoot>true</addSourceRoot>
                                    <sourceFolder>${project.basedir}/src/main/graphql/books</sourceFolder>
                                    <schemaPath>${project.basedir}/src/main/graphql/books/schema.json</schemaPath>
                                    <includes>
                                        <include>**/*.graphql</include>
                                        <include>**/*.gql</include>
                                        <include>**/*.json</include>
                                        <include>**/*.sdl"</include>
                                    </includes>
                                    <excludes>
                                        **/*.kakah
                                    </excludes>
                                    <compilationUnit>
                                        <name>books</name>
                                        <outputDirectory>
                                            ${project.build.directory}/generated-sources/graphql-client/books/
                                        </outputDirectory>
                                        <testDirectory>
                                            ${project.build.directory}/generated-sources/graphql-client/books/test/
                                        </testDirectory>
                                        <debugDirectory>
                                            ${project.build.directory}/generated-sources/graphql-client/books/debug/
                                        </debugDirectory>
                                        <generateOperationDescriptors>true</generateOperationDescriptors>
                                        <compilerParams>
                                            <rootFolders>
                                                <rootFolder>${project.basedir}/src/main/graphql/books/</rootFolder>
                                            </rootFolders>
                                            <generateKotlinModels>true</generateKotlinModels>
                                            <scalarsMapping>
                                                <Long>
                                                    <targetName>java.lang.Long</targetName>
                                                </Long>
                                            </scalarsMapping>
                                            <operationIdGeneratorClass></operationIdGeneratorClass>
                                            <schemaPackageName>com.lahzouz.apollo.graphql.client</schemaPackageName>
                                            <packageName>com.lahzouz.apollo.graphql.client</packageName>
                                            <codegenModels>OPERATION</codegenModels>
                                            <flattenModels>true</flattenModels>
                                            <generateApolloMetadata>false</generateApolloMetadata>
                                            <generateAsInternal>false</generateAsInternal>
                                            <generateFilterNotNull>false</generateFilterNotNull>
                                            <generateFragmentImplementations>false</generateFragmentImplementations>
                                            <generateResponseFields>false</generateResponseFields>
                                            <generateQueryDocument>true</generateQueryDocument>
                                            <generateSchema>false</generateSchema>
                                            <generateTestBuilders>false</generateTestBuilders>
                                            <generateOptionalOperationVariables>false
                                            </generateOptionalOperationVariables>
                                            <nullableFieldStyle>NONE</nullableFieldStyle>
                                            <useSemanticNaming>true</useSemanticNaming>
                                            <targetLanguage>KOTLIN_1_5</targetLanguage>
                                            <sealedClassesForEnumsMatching></sealedClassesForEnumsMatching>
                                            <alwaysGenerateTypesMatching></alwaysGenerateTypesMatching>
                                            <metadataOutputFile>
                                                ${project.build.directory}/generated/metadata/apollo/books/metadata.json
                                            </metadataOutputFile>
                                        </compilerParams>
                                    </compilationUnit>
                                    <introspection>
                                        <enabled>false</enabled>
                                        <endpointUrl></endpointUrl>
                                        <headers></headers>
                                        <schemaFile>${project.basedir}/src/main/graphql/books/schema.json</schemaFile>
                                        <connectTimeoutSeconds>10</connectTimeoutSeconds>
                                        <readTimeoutSeconds>10</readTimeoutSeconds>
                                        <writeTimeoutSeconds>10</writeTimeoutSeconds>
                                        <useSelfSignedCertificat>false</useSelfSignedCertificat>
                                        <useGzip>false</useGzip>
                                        <prettyPrint>false</prettyPrint>
                                    </introspection>
                                </books-api>
                            </services>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by aoudiamoncef** [comment]
Hi @psupelek 

You have a complete guide for Gradle in [Apollo Kotlin](https://www.apollographql.com/docs/kotlin/advanced/plugin-configuration)
