### ISSUE TITLE
scalarsMapping documentation

### ISSUE THREAD

**Issue by bnbalint** [aoudiamoncef/apollo-client-maven-plugin#90]
I've been having some issues with getting the **scalarsMapping** part of the documentation to work (after working through some things, I **think** the documentation might indicate the tag is **scalarsMapping**, but it in fact needs to be **customScalarsMapping** - can you confirm or deny that?)

Can you tell me how to replicate this functionality from gradle?

apollo {
    generateKotlinModels.set(true)
    packageName.set("src.main.graphql")
    **mapScalarToKotlinLong("BigInt")**
    schemaFile.set(file("src/main/graphql/schema.graphqls"))
    **mapScalar("Datetime", "java.time.LocalDateTime", "com.segmint.eventsPublisher.JavaLocalDateTimeAdapter")**
}

mapScalarToKotlinLong documented here --> https://www.apollographql.com/docs/kotlin/kdoc/apollo-gradle-plugin-external/com.apollographql.apollo3.gradle.internal/-default-service/map-scalar-to-kotlin-long.html

Thank you!

**Comment by aoudiamoncef** [comment]
Cc @martinbonnin

**Comment by martinbonnin** [comment]
Wildly untested but I would go for something like this?

```xml
    <scalarsMapping>
        <BigInt>kotlin.Long</BigInt>
        <Datetime>java.time.LocalDateTime</Datetime>
    </scalarsMapping>
```

**Comment by bnbalint** [comment]
That was my initial guess as well, but the compiler gets angry because it ends up not recognizing kotlin.Long. It turns out my sources are being generated as Java files, not kotlin files. Should `<generateKotlinModels>true</generateKotlinModels>` be creating kotlin files?

Do I have something fundamentally wrong with my configuration? I also can't get the scalarsMapping tag to work .. only customScalarsMapping - which makes me wonder if I have something wrong on a larger scale.

`            <plugin>
                <groupId>com.github.aoudiamoncef</groupId>
                <artifactId>apollo-client-maven-plugin</artifactId>
                <version>5.0.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>

                            <services>
                                <eventsPublisher-api>
                                    <sourceFolder>${project.basedir}/src/main/graphql/eventsPublisher</sourceFolder>
                                    <schemaPath>${project.basedir}/src/main/graphql/eventsPublisher/schema.json</schemaPath>
                                    <compilationUnit>
                                        <name>eventsPublisher</name>
                                        <compilerParams>
                                            <schemaPackageName>src.main.graphql</schemaPackageName>
                                            <generateKotlinModels>true</generateKotlinModels>
                                            <customScalarsMapping>
                                                <BigInt>kotlin.Long</BigInt>
                                                <Datetime>com.foo.eventsPublisher.JavaLocalDateTimeAdapter</Datetime>
                                            </customScalarsMapping>
                                        </compilerParams>
                                    </compilationUnit>
                                </eventsPublisher-api>
                            </services>
                        </configuration>
                    </execution>
                </executions>
            </plugin>`

**Comment by bnbalint** [comment]
After a lot of trial and error, I eventually figured out this **version** and **configuration** work:

```
            <plugin>
                <groupId>com.github.aoudiamoncef</groupId>
                <artifactId>apollo-client-maven-plugin</artifactId>
                <version>7.0.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>

                            <services>
                                <eventsPublisher-api>
                                    <sourceFolder>${project.basedir}/src/main/graphql/eventsPublisher</sourceFolder>
                                    <schemaPath>${project.basedir}/src/main/graphql/eventsPublisher/schema.json</schemaPath>
                                    <compilationUnit>
                                        <name>eventsPublisher</name>
                                        <compilerParams>
                                            <schemaPackageName>src.main.graphql</schemaPackageName>
                                            <generateKotlinModels>true</generateKotlinModels>
                                            <targetLanguage>KOTLIN_1_5</targetLanguage>
                                            <scalarsMapping>
                                                <BigInt>
                                                    <targetName>kotlin.Long</targetName>
                                                </BigInt>
                                                <Datetime>
                                                    <targetName>java.time.LocalDateTime</targetName>
                                                    <expression>com.foo.eventsPublisher.LocalDateTimeGraphQLAdapter()</expression>
                                                </Datetime>
                                            </scalarsMapping>
                                        </compilerParams>
                                    </compilationUnit>
                                </eventsPublisher-api>
                            </services>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
