### ISSUE TITLE
Introspection headers syntax

### ISSUE THREAD

**Issue by schmidltomas** [aoudiamoncef/apollo-client-maven-plugin#95]
Hey, thanks for this cool plugin @aoudiamoncef. I'm trying to configure the introspection endpoint, but my GraphQL service requires an Authorization header with API key. What's the correct syntax for `<headers>` tag of the `<introspection>` section? The README leaves it blank:

```
<headers></headers>
```

I've tried:
```
<headers>
  <header>
    Authorization: Bearer xxx
  </header>
</headers>
```
Where xxx is the real token. I've tried various placings of various quotation marks, but I'm still getting: 
```
Execution default of goal com.github.aoudiamoncef:apollo-client-maven-plugin:7.0.0:generate failed: Cannot get schema from https://my.service/grapql: 401:
```
Thanks a lot.

**Comment by aoudiamoncef** [comment]
Hi @schmidltomas 

You can try this:

```xml
<introspection>
  <url>https://my.service/graphql</url>
  <headers>
    <header>
      <key>Authorization</key>
      <value>Bearer xxx</value>
    </header>
  </headers>
</introspection>
```

Thanks

**Comment by schmidltomas** [comment]
Thanks for the reply. Now I'm getting:
```
[ERROR] Failed to execute goal com.github.aoudiamoncef:apollo-client-maven-plugin:7.0.0:generate (default) on project my-project: Execution default of goal com.github.aoudiamoncef:apollo-client-maven-plugin:7.0.0:generate failed: Parameter specified as non-null is null: method okhttp3.Request$Builder.addHeader, parameter value
```
Doesn't this imply a syntax error? In my previous tries it seemed the plugin actually called the GraphQL service.

Also I should note that the token is valid. I'm using it in `ApolloClient` itself, where it works just fine.

**Comment by aoudiamoncef** [comment]
We have a [complete](https://github.com/aoudiamoncef/spring-boot-apollo-graphql/blob/main/pom.xml) example:

```xml
<headers>
    <Authorization>Bearer token</Authorization>
</headers>
```

**Comment by schmidltomas** [comment]
That went straight over my head! Now it works, thanks.
